### ISSUE TITLE
heap-buffer-overflow read in feed_table_tag()

### ISSUE THREAD

**Issue by kcwu** [tats/w3m#60]
input (xxd [cases/tats-w3m-60](https://github.com/kcwu/fuzzing-w3m/blob/master/cases/tats-w3m-60))
```
00000000: 3c74 6162 6c65 3e3c 7468 2063 6f6c 7370  <table><th colsp
00000010: 616e 3d39 3030 3e3c 7468 3e              an=900><th>
```

how to reproduce:
```
ASAN_OPTIONS=abort_on_error=1:detect_leaks=0 LD_LIBRARY_PATH=./notgc ./w3m-tats.asan -T text/html -dump cases/tats-w3m-60
```

stderr:
```
=================================================================
==3694446==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61500000fc80 at pc 0x000000618fc4 bp 0x7ffe43efa570 sp 0x7ffe43efa568
READ of size 2 at 0x61500000fc80 thread T0
    #0 0x618fc3 in feed_table_tag /targets/w3m-tats/table.c:2595:9
    #1 0x6145d5 in feed_table /targets/w3m-tats/table.c:3145:14
    #2 0x591bcc in HTMLlineproc0 /targets/w3m-tats/file.c:6424:14
    #3 0x5a5a0c in loadHTMLstream /targets/w3m-tats/file.c:7252:2
    #4 0x55bbf8 in loadHTMLBuffer /targets/w3m-tats/file.c:6781:5
    #5 0x55ee64 in loadSomething /targets/w3m-tats/file.c:224:16
    #6 0x5535ac in loadGeneralFile /targets/w3m-tats/file.c:2241:6
    #7 0x4f9202 in main /targets/w3m-tats/main.c:1017:12
    #8 0x7f1bf5abef44 in __libc_start_main /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:287
    #9 0x41bf25 in _start (/w3m-tats.asan+0x41bf25)

0x61500000fc80 is located 0 bytes to the right of 512-byte region [0x61500000fa80,0x61500000fc80)
allocated by thread T0 here:
    #0 0x4c6288 in __interceptor_malloc (/w3m-tats.asan+0x4c6288)
    #1 0x7f1bf720cc21 in GC_malloc_atomic /notgc/notgc.c:275
    #2 0x618e1c in feed_table_tag /targets/w3m-tats/table.c:2594:2
    #3 0x6145d5 in feed_table /targets/w3m-tats/table.c:3145:14
    #4 0x591bcc in HTMLlineproc0 /targets/w3m-tats/file.c:6424:14
    #5 0x5a5a0c in loadHTMLstream /targets/w3m-tats/file.c:7252:2
    #6 0x55bbf8 in loadHTMLBuffer /targets/w3m-tats/file.c:6781:5
    #7 0x55ee64 in loadSomething /targets/w3m-tats/file.c:224:16
    #8 0x5535ac in loadGeneralFile /targets/w3m-tats/file.c:2241:6
    #9 0x4f9202 in main /targets/w3m-tats/main.c:1017:12
    #10 0x7f1bf5abef44 in __libc_start_main /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:287

SUMMARY: AddressSanitizer: heap-buffer-overflow /targets/w3m-tats/table.c:2595:9 in feed_table_tag
Shadow bytes around the buggy address:
  0x0c2a7fff9f40: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c2a7fff9f50: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c2a7fff9f60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c2a7fff9f70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c2a7fff9f80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c2a7fff9f90:[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c2a7fff9fa0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c2a7fff9fb0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c2a7fff9fc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c2a7fff9fd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 fa fa
  0x0c2a7fff9fe0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==3694446==ABORTING
```

This is detected with help of dummy libgc wrapper. See http://github.com/kcwu/fuzzing-w3m/notgc for detail.
More detail to reproduce please see http://github.com/kcwu/fuzzing-w3m

For your convenience,
gdbline:
LD_LIBRARY_PATH=./notgc ASAN_OPTIONS=abort_on_error=1:detect_leaks=0 gdb --args ./w3m-tats.asan -T text/html -dump cases/tats-w3m-60

This is found by afl-fuzz.

**Comment by kcwu** [comment]
```
2595            while (tbl->tabattr[tbl->row][tbl->col]) {
2596                tbl->col++;
2597            }
2598            if (tbl->col > MAXCOL - 1) {
2599                tbl->col = prev_col;
```
where `tbl->col=256` but `tbl->tabattr[tbl->row][]` is allocated with fixed size in `check_row()`
```
379         t->tabattr[row] = NewAtom_N(table_attr, MAXCOL);
```
where `MAXCOL=256`.

The good news is, line 2598 will check the value of `tbl->col`.

**Comment by tats** [comment]
Fixed, thank you.
