### ISSUE TITLE
heap-buffer-overflow write in HTMLlineproc2body()

### ISSUE THREAD

**Issue by kcwu** [tats/w3m#61]
input (xxd [cases/tats-w3m-61](https://github.com/kcwu/fuzzing-w3m/blob/master/cases/tats-w3m-61))
```
00000000: 3c62 7574 746f 6e20 7661 6c75 653d 2722  <button value='"
00000010: 3e3c 4120 6872 6566 3d3e 3c2f 613e 273e  ><A href=></a>'>
00000020: 303c 703e                                0<p>
```

how to reproduce:
```
ASAN_OPTIONS=abort_on_error=1:detect_leaks=0 LD_LIBRARY_PATH=./notgc ./w3m-tats.asan -T text/html -dump cases/tats-w3m-61
```

stderr:
```
=================================================================
==3694512==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61300000dafc at pc 0x00000059bcff bp 0x7fffbc8c7af0 sp 0x7fffbc8c7ae8
WRITE of size 4 at 0x61300000dafc thread T0
    #0 0x59bcfe in HTMLlineproc2body /targets/w3m-tats/file.c:5731:49
    #1 0x59702e in HTMLlineproc2 /targets/w3m-tats/file.c:6198:5
    #2 0x5a63ee in loadHTMLstream /targets/w3m-tats/file.c:7289:5
    #3 0x55bbf8 in loadHTMLBuffer /targets/w3m-tats/file.c:6781:5
    #4 0x55ee64 in loadSomething /targets/w3m-tats/file.c:224:16
    #5 0x5535ac in loadGeneralFile /targets/w3m-tats/file.c:2241:6
    #6 0x4f9202 in main /targets/w3m-tats/main.c:1017:12
    #7 0x7f3a4ea10f44 in __libc_start_main /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:287
    #8 0x41bf25 in _start (/w3m-tats.asan+0x41bf25)

0x61300000dafc is located 4 bytes to the left of 360-byte region [0x61300000db00,0x61300000dc68)
allocated by thread T0 here:
    #0 0x4c6288 in __interceptor_malloc (/w3m-tats.asan+0x4c6288)
    #1 0x7f3a5015ec21 in GC_malloc_atomic /notgc/notgc.c:275
    #2 0x59c7cc in HTMLlineproc2body /targets/w3m-tats/file.c:5845:5
    #3 0x59702e in HTMLlineproc2 /targets/w3m-tats/file.c:6198:5
    #4 0x5a63ee in loadHTMLstream /targets/w3m-tats/file.c:7289:5
    #5 0x55bbf8 in loadHTMLBuffer /targets/w3m-tats/file.c:6781:5
    #6 0x55ee64 in loadSomething /targets/w3m-tats/file.c:224:16
    #7 0x5535ac in loadGeneralFile /targets/w3m-tats/file.c:2241:6
    #8 0x4f9202 in main /targets/w3m-tats/main.c:1017:12
    #9 0x7f3a4ea10f44 in __libc_start_main /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:287

SUMMARY: AddressSanitizer: heap-buffer-overflow /targets/w3m-tats/file.c:5731:49 in HTMLlineproc2body
Shadow bytes around the buggy address:
  0x0c267fff9b00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c267fff9b10: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c267fff9b20: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c267fff9b30: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c267fff9b40: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c267fff9b50: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa[fa]
  0x0c267fff9b60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c267fff9b70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c267fff9b80: 00 00 00 00 00 00 00 00 00 00 00 00 00 fa fa fa
  0x0c267fff9b90: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c267fff9ba0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==3694512==ABORTING
```

This is detected with help of dummy libgc wrapper. See http://github.com/kcwu/fuzzing-w3m/notgc for detail.
More detail to reproduce please see http://github.com/kcwu/fuzzing-w3m

For your convenience,
gdbline:
LD_LIBRARY_PATH=./notgc ASAN_OPTIONS=abort_on_error=1:detect_leaks=0 gdb --args ./w3m-tats.asan -T text/html -dump cases/tats-w3m-61

This is found by afl-fuzz.

**Comment by kcwu** [comment]
```
#6  0x000000000059bcff in HTMLlineproc2body (buf=0x61500000fd00, feed=0x5b3910 <textlist_feed>, llimit=-1) at file.c:5731
5731                                    buf->hmarklist->marks[a_href->hseq].invalid = 1;
(gdb) p a_href->hseq
$1 = -1
```

**Comment by tats** [comment]
Fixed, thank you.
