### ISSUE TITLE
heap-buffer-overflow read in shiftAnchorPosition()

### ISSUE THREAD

**Issue by kcwu** [tats/w3m#62]
input (xxd [cases/tats-w3m-62](https://github.com/kcwu/fuzzing-w3m/blob/master/cases/tats-w3m-62))
```
00000000: 3c74 6162 6c65 3e3c 6275 7474 6f6e 3e3c  <table><button><
00000010: 7461 626c 653e 3c74 6578 7461 7265 613e  table><textarea>
00000020: d1af                                     ..
```

how to reproduce:
```
ASAN_OPTIONS=abort_on_error=1:detect_leaks=0 LD_LIBRARY_PATH=./notgc ./w3m-tats.asan -T text/html -dump cases/tats-w3m-62
```

stderr:
```
=================================================================
==3694575==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61300000d934 at pc 0x0000006d2f6a bp 0x7fff4cc4cea0 sp 0x7fff4cc4ce98
READ of size 4 at 0x61300000d934 thread T0
    #0 0x6d2f69 in shiftAnchorPosition /targets/w3m-tats/anchor.c:554:48
    #1 0x63079e in formUpdateBuffer /targets/w3m-tats/form.c:505:3
    #2 0x631697 in formResetBuffer /targets/w3m-tats/form.c:272:2
    #3 0x55bdd8 in loadHTMLBuffer /targets/w3m-tats/file.c:6787:2
    #4 0x55ee64 in loadSomething /targets/w3m-tats/file.c:224:16
    #5 0x5535ac in loadGeneralFile /targets/w3m-tats/file.c:2241:6
    #6 0x4f9202 in main /targets/w3m-tats/main.c:1017:12
    #7 0x7f6e29bcff44 in __libc_start_main /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:287
    #8 0x41bf25 in _start (/w3m-tats.asan+0x41bf25)

0x61300000d934 is located 12 bytes to the left of 360-byte region [0x61300000d940,0x61300000daa8)
allocated by thread T0 here:
    #0 0x4c6288 in __interceptor_malloc (/w3m-tats.asan+0x4c6288)
    #1 0x7f6e2b31dc21 in GC_malloc_atomic /notgc/notgc.c:275
    #2 0x59c7cc in HTMLlineproc2body /targets/w3m-tats/file.c:5845:5
    #3 0x59702e in HTMLlineproc2 /targets/w3m-tats/file.c:6198:5
    #4 0x5a63ee in loadHTMLstream /targets/w3m-tats/file.c:7289:5
    #5 0x55bbf8 in loadHTMLBuffer /targets/w3m-tats/file.c:6781:5
    #6 0x55ee64 in loadSomething /targets/w3m-tats/file.c:224:16
    #7 0x5535ac in loadGeneralFile /targets/w3m-tats/file.c:2241:6
    #8 0x4f9202 in main /targets/w3m-tats/main.c:1017:12
    #9 0x7f6e29bcff44 in __libc_start_main /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:287

SUMMARY: AddressSanitizer: heap-buffer-overflow /targets/w3m-tats/anchor.c:554:48 in shiftAnchorPosition
Shadow bytes around the buggy address:
  0x0c267fff9ad0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c267fff9ae0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c267fff9af0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c267fff9b00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c267fff9b10: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c267fff9b20: fa fa fa fa fa fa[fa]fa 00 00 00 00 00 00 00 00
  0x0c267fff9b30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c267fff9b40: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c267fff9b50: 00 00 00 00 00 fa fa fa fa fa fa fa fa fa fa fa
  0x0c267fff9b60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c267fff9b70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==3694575==ABORTING
```

This is detected with help of dummy libgc wrapper. See http://github.com/kcwu/fuzzing-w3m/notgc for detail.
More detail to reproduce please see http://github.com/kcwu/fuzzing-w3m

For your convenience,
gdbline:
LD_LIBRARY_PATH=./notgc ASAN_OPTIONS=abort_on_error=1:detect_leaks=0 gdb --args ./w3m-tats.asan -T text/html -dump cases/tats-w3m-62

This is found by afl-fuzz.

**Comment by kcwu** [comment]
This one is serious because the next line will be overflow write (`a->hseq=-1`)
```
554                 if (hl && hl->marks && hl->marks[a->hseq].line == line)
555                     hl->marks[a->hseq].pos = a->start.pos;
```

**Comment by tats** [comment]
Fixed, thank you.
