### ISSUE TITLE
heap-buffer-overflow read in getMetaRefreshParam()

### ISSUE THREAD

**Issue by kcwu** [tats/w3m#63]
input (xxd [cases/tats-w3m-63](https://github.com/kcwu/fuzzing-w3m/blob/master/cases/tats-w3m-63))
```
00000000: 3c6d 6574 6120 6874 7470 2d65 7175 6976  <meta http-equiv
00000010: 3d22 7265 6672 6573 6822 636f 6e74 656e  ="refresh"conten
00000020: 743d 5552 4c3d 3e                        t=URL=>
```

how to reproduce:
```
ASAN_OPTIONS=abort_on_error=1:detect_leaks=0 LD_LIBRARY_PATH=./notgc ./w3m-tats.asan -T text/html -dump cases/tats-w3m-63
```

stderr:
```
=================================================================
==3694633==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200000c5cf at pc 0x0000005765fd bp 0x7ffda35a9e00 sp 0x7ffda35a9df8
READ of size 1 at 0x60200000c5cf thread T0
    #0 0x5765fc in getMetaRefreshParam /targets/w3m-tats/file.c:4381:10
    #1 0x58de57 in HTMLtagproc1 /targets/w3m-tats/file.c:5197:25
    #2 0x5927e3 in HTMLlineproc0 /targets/w3m-tats/file.c:6477:10
    #3 0x5a5a0c in loadHTMLstream /targets/w3m-tats/file.c:7252:2
    #4 0x55bbf8 in loadHTMLBuffer /targets/w3m-tats/file.c:6781:5
    #5 0x55ee64 in loadSomething /targets/w3m-tats/file.c:224:16
    #6 0x5535ac in loadGeneralFile /targets/w3m-tats/file.c:2241:6
    #7 0x4f9202 in main /targets/w3m-tats/main.c:1017:12
    #8 0x7fb493b93f44 in __libc_start_main /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:287
    #9 0x41bf25 in _start (/w3m-tats.asan+0x41bf25)

0x60200000c5cf is located 1 bytes to the left of 1-byte region [0x60200000c5d0,0x60200000c5d1)
allocated by thread T0 here:
    #0 0x4c6288 in __interceptor_malloc (/w3m-tats.asan+0x4c6288)
    #1 0x7fb4952e1c21 in GC_malloc_atomic /notgc/notgc.c:275
    #2 0x576500 in getMetaRefreshParam /targets/w3m-tats/file.c:4379:14
    #3 0x58de57 in HTMLtagproc1 /targets/w3m-tats/file.c:5197:25
    #4 0x5927e3 in HTMLlineproc0 /targets/w3m-tats/file.c:6477:10
    #5 0x5a5a0c in loadHTMLstream /targets/w3m-tats/file.c:7252:2
    #6 0x55bbf8 in loadHTMLBuffer /targets/w3m-tats/file.c:6781:5
    #7 0x55ee64 in loadSomething /targets/w3m-tats/file.c:224:16
    #8 0x5535ac in loadGeneralFile /targets/w3m-tats/file.c:2241:6
    #9 0x4f9202 in main /targets/w3m-tats/main.c:1017:12
    #10 0x7fb493b93f44 in __libc_start_main /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:287

SUMMARY: AddressSanitizer: heap-buffer-overflow /targets/w3m-tats/file.c:4381:10 in getMetaRefreshParam
Shadow bytes around the buggy address:
  0x0c047fff9860: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9870: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9880: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9890: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff98a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c047fff98b0: fa fa fa fa fa fa fa fa fa[fa]01 fa fa fa 00 00
  0x0c047fff98c0: fa fa 00 00 fa fa 00 00 fa fa 00 00 fa fa 00 00
  0x0c047fff98d0: fa fa 04 fa fa fa 00 00 fa fa 00 00 fa fa 00 00
  0x0c047fff98e0: fa fa 00 01 fa fa 00 00 fa fa 00 00 fa fa 00 00
  0x0c047fff98f0: fa fa 04 fa fa fa 04 fa fa fa 00 00 fa fa fd fd
  0x0c047fff9900: fa fa fd fa fa fa fd fa fa fa 00 00 fa fa 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==3694633==ABORTING
```

This is detected with help of dummy libgc wrapper. See http://github.com/kcwu/fuzzing-w3m/notgc for detail.
More detail to reproduce please see http://github.com/kcwu/fuzzing-w3m

For your convenience,
gdbline:
LD_LIBRARY_PATH=./notgc ASAN_OPTIONS=abort_on_error=1:detect_leaks=0 gdb --args ./w3m-tats.asan -T text/html -dump cases/tats-w3m-63

This is found by afl-fuzz.

**Comment by kcwu** [comment]
This one is serious because the next two lines will be overflow write (`s_tmp->length=0`)
```
4381                if (s_tmp->ptr[s_tmp->length - 1] == '\"'          /* " */
4382                   || s_tmp->ptr[s_tmp->length - 1] == '\'') {     /* ' */
4383                    s_tmp->length--;
4384                    s_tmp->ptr[s_tmp->length] = '\0';
```

**Comment by tats** [comment]
Fixed, thank you.
