### ISSUE TITLE
SEGV in flushline()

### ISSUE THREAD

**Issue by kcwu** [tats/w3m#66]
input (xxd [cases/tats-w3m-66](https://github.com/kcwu/fuzzing-w3m/blob/master/cases/tats-w3m-66))
```
00000000: 303c 696e 7075 7420 7479 7065 3d22 696d  0<input type="im
00000010: 6167 6522 6865 6967 6874 3d30 2073 7263  age"height=0 src
00000020: 3d30 2077 6964 7468 3d33 3030 3030 303e  =0 width=300000>
00000030: 3c69 3e3c 703e                           <i><p>
```

how to reproduce:
```
ASAN_OPTIONS=abort_on_error=1:detect_leaks=0 LD_LIBRARY_PATH=./notgc ./w3m-tats.asan -T text/html -dump cases/tats-w3m-66
```

stderr:
```
ASAN:DEADLYSIGNAL
=================================================================
==3694846==ERROR: AddressSanitizer: SEGV on unknown address 0x62efffff9729 (pc 0x7f8f893e49da bp 0x7ffdf74d8930 sp 0x7ffdf74d80a8 T0)
    #0 0x7f8f893e49d9 in strlen /build/eglibc-oGUzwX/eglibc-2.19/string/../sysdeps/x86_64/strlen.S:76
    #1 0x44b7ad in strlen (/w3m-tats.asan+0x44b7ad)
    #2 0x6e355d in Strnew_charp /targets/w3m-tats/Str.c:67:9
    #3 0x56129c in flushline /targets/w3m-tats/file.c:2789:9
    #4 0x577f87 in HTMLtagproc1 /targets/w3m-tats/file.c:4490:6
    #5 0x5927e3 in HTMLlineproc0 /targets/w3m-tats/file.c:6477:10
    #6 0x5a5a0c in loadHTMLstream /targets/w3m-tats/file.c:7252:2
    #7 0x55bbf8 in loadHTMLBuffer /targets/w3m-tats/file.c:6781:5
    #8 0x55ee64 in loadSomething /targets/w3m-tats/file.c:224:16
    #9 0x5535ac in loadGeneralFile /targets/w3m-tats/file.c:2241:6
    #10 0x4f9202 in main /targets/w3m-tats/main.c:1017:12
    #11 0x7f8f8937df44 in __libc_start_main /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:287
    #12 0x41bf25 in _start (/w3m-tats.asan+0x41bf25)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /build/eglibc-oGUzwX/eglibc-2.19/string/../sysdeps/x86_64/strlen.S:76 in strlen
==3694846==ABORTING
```

This is detected with help of dummy libgc wrapper. See http://github.com/kcwu/fuzzing-w3m/notgc for detail.
More detail to reproduce please see http://github.com/kcwu/fuzzing-w3m

For your convenience,
gdbline:
LD_LIBRARY_PATH=./notgc ASAN_OPTIONS=abort_on_error=1:detect_leaks=0 gdb --args ./w3m-tats.asan -T text/html -dump cases/tats-w3m-66

This is found by afl-fuzz.

**Comment by kcwu** [comment]
The string pointer is got from `has_hidden_link()`
```
2303          return line->ptr + p->offset;
```
where `p->offset=-27863`.
The type of `p->offset` is `short` . It was overflowed earlier in `proc_mchar()`.

**Comment by kcwu** [comment]
I don't understand why it cannot reproduce without the dummy libgc wrapper. Probably there are  other issues.

**Comment by kcwu** [comment]
dedup to #64
