### ISSUE TITLE
SEGV in calcPosition()

### ISSUE THREAD

**Issue by kcwu** [tats/w3m#69]
input (`xxd cases/tats-w3m-69`)
```
00000000: 3c74 6162 6c65 3e30 3030 3030 3c74 723e  <table>00000<tr>
00000010: 3c74 643e 3c69 6e70 7574 2074 7970 653d  <td><input type=
00000020: 2269 6d61 6765 2268 6569 6768 743d 3020  "image"height=0
00000030: 7372 633d 3020 7769 6474 683d 3330 3030  src=0 width=3000
00000040: 3030 3e3c 6474 3e30 3030 3030 0a30 3d30  00><dt>00000.0=0
00000050: 0030 3d30 e830 9730 3e30 3e30 d230 2030  .0=0.0.0>0>0.0 0
00000060: 8330 3c74 643e 303c 7461 626c 653e 303c  .0<td>0<table>0<
00000070: 7461 626c 653e 303c 7461 626c 653e 3c74  table>0<table><t
00000080: 6578 7461 7265 6120 726f 7773 3d32 383e  extarea rows=28>
00000090: 3c74 643e 303c 7461 626c 653e 3c74 6578  <td>0<table><tex
000000a0: 7461 7265 6120 726f 7773 3d32 383e       tarea rows=28>
```

how to reproduce:
```
ASAN_OPTIONS=abort_on_error=1:detect_leaks=0 LD_LIBRARY_PATH=./notgc ./w3m-tats.asan -T text/html -dump cases/tats-w3m-69
```

stderr:
```
ASAN:DEADLYSIGNAL
=================================================================
==2732477==ERROR: AddressSanitizer: SEGV on unknown address 0x7f108ea22574 (pc 0x0000005cec44 bp 0x7ffef052f390 sp 0x7ffef052f2c0 T0)
    #0 0x5cec43 in calcPosition /targets/w3m-tats/etc.c:535:12
    #1 0x62fe06 in formUpdateBuffer /targets/w3m-tats/form.c:483:8
    #2 0x631697 in formResetBuffer /targets/w3m-tats/form.c:272:2
    #3 0x55bdd8 in loadHTMLBuffer /targets/w3m-tats/file.c:6787:2
    #4 0x55ee64 in loadSomething /targets/w3m-tats/file.c:224:16
    #5 0x5535ac in loadGeneralFile /targets/w3m-tats/file.c:2241:6
    #6 0x4f9202 in main /targets/w3m-tats/main.c:1017:12
    #7 0x7f1091e5df44 in __libc_start_main /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:287
    #8 0x41bf25 in _start (/w3m-tats.asan+0x41bf25)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /targets/w3m-tats/etc.c:535:12 in calcPosition
==2732477==ABORTING
```

This is detected with help of dummy libgc wrapper. See http://github.com/kcwu/fuzzing-w3m/notgc for detail.
More detail to reproduce please see http://github.com/kcwu/fuzzing-w3m

For your convenience,
gdbline:
LD_LIBRARY_PATH=./notgc ASAN_OPTIONS=abort_on_error=1:detect_leaks=0 gdb --args ./w3m-tats.asan -T text/html -dump cases/tats-w3m-69

This is found by afl-fuzz.

**Comment by kcwu** [comment]
This case is not very reliable. I guess it is related to uninitialized variable.

**Comment by kcwu** [comment]
```
Program received signal SIGSEGV, Segmentation fault.
0x00000000005cec44 in calcPosition (l=0x631000050800 ' ' <repeats 200 times>..., pr=0x7ffff7e0e800, len=65580, pos=-74915, bpos=0, mode=0) at etc.c:535
535         return realColumn[pos];
(gdb) p pos
$1 = -74915
```
The negative value came from formUpdateBuffer()
```
505                  shiftAnchorPosition(buf->formitem, buf->hmarklist,
506                                      a->start.line, spos, pos - epos);
```
whre `pos=37492`, `epos=112500`.

**Comment by tats** [comment]
Fixed, thank you.
