### ISSUE TITLE
heap-buffer-overflow read in visible_length()

### ISSUE THREAD

**Issue by kcwu** [tats/w3m#73]
similar to issue #57 

input (`xxd cases/tats-w3m-73`)
```
00000000: 3c74 6162 6c65 3e26 8c3c                 <table>&.<
```

how to reproduce:
```
ASAN_OPTIONS=abort_on_error=1:detect_leaks=0 LD_LIBRARY_PATH=./notgc ./w3m-tats.asan -T text/html -dump cases/tats-w3m-73
```

stderr:
```
=================================================================
==827466==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60300000d110 at pc 0x0000005f7370 bp 0x7fff6568cf30 sp 0x7fff6568cf28
READ of size 1 at 0x60300000d110 thread T0
    #0 0x5f736f in visible_length /targets/w3m-tats/table.c:432:12
    #1 0x616c31 in feed_table /targets/w3m-tats/table.c:3250:23
    #2 0x591c7c in HTMLlineproc0 /targets/w3m-tats/file.c:6434:14
    #3 0x5a5d4c in loadHTMLstream /targets/w3m-tats/file.c:7265:2
    #4 0x55bbf8 in loadHTMLBuffer /targets/w3m-tats/file.c:6794:5
    #5 0x55ee64 in loadSomething /targets/w3m-tats/file.c:224:16
    #6 0x5535ac in loadGeneralFile /targets/w3m-tats/file.c:2241:6
    #7 0x4f9202 in main /targets/w3m-tats/main.c:1017:12
    #8 0x7fed79631f44 in __libc_start_main /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:287
    #9 0x41bf25 in _start (/w3m-tats.asan+0x41bf25)

0x60300000d110 is located 0 bytes to the right of 32-byte region [0x60300000d0f0,0x60300000d110)
allocated by thread T0 here:
    #0 0x4c6288 in __interceptor_malloc (/w3m-tats.asan+0x4c6288)
    #1 0x7fed7ad7fc21 in GC_malloc_atomic /notgc/notgc.c:275
    #2 0x615121 in feed_table /targets/w3m-tats/table.c:3191:8
    #3 0x591c7c in HTMLlineproc0 /targets/w3m-tats/file.c:6434:14
    #4 0x5a5d4c in loadHTMLstream /targets/w3m-tats/file.c:7265:2
    #5 0x55bbf8 in loadHTMLBuffer /targets/w3m-tats/file.c:6794:5
    #6 0x55ee64 in loadSomething /targets/w3m-tats/file.c:224:16
    #7 0x5535ac in loadGeneralFile /targets/w3m-tats/file.c:2241:6
    #8 0x4f9202 in main /targets/w3m-tats/main.c:1017:12
    #9 0x7fed79631f44 in __libc_start_main /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:287

SUMMARY: AddressSanitizer: heap-buffer-overflow /targets/w3m-tats/table.c:432:12 in visible_length
Shadow bytes around the buggy address:
  0x0c067fff99d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff99e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff99f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff9a00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff9a10: fa fa fa fa fa fa fa fa 00 00 00 00 fa fa 00 00
=>0x0c067fff9a20: 00 00[fa]fa 00 00 00 00 fa fa 00 00 00 00 fa fa
  0x0c067fff9a30: 00 00 00 02 fa fa 00 00 00 fa fa fa 00 00 00 00
  0x0c067fff9a40: fa fa 00 00 00 00 fa fa 00 00 00 00 fa fa fd fd
  0x0c067fff9a50: fd fd fa fa 00 00 00 00 fa fa 00 00 00 00 fa fa
  0x0c067fff9a60: 00 00 00 fa fa fa 00 00 00 00 fa fa 00 00 02 fa
  0x0c067fff9a70: fa fa 00 00 02 fa fa fa 00 00 00 00 fa fa 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==827466==ABORTING
```

This is detected with help of dummy libgc wrapper. See http://github.com/kcwu/fuzzing-w3m/notgc for detail.
More detail to reproduce please see http://github.com/kcwu/fuzzing-w3m

For your convenience,
gdbline:
LD_LIBRARY_PATH=./notgc ASAN_OPTIONS=abort_on_error=1:detect_leaks=0 gdb --args ./w3m-tats.asan -T text/html -dump cases/tats-w3m-73

this is found by afl-fuzz

**Comment by kcwu** [comment]
table.c
```
437             n = get_mclen(str);
...
494             str += n;
```
`n=3`, `str` jump beyond the end of string.

**Comment by kcwu** [comment]
Given issue 73,74,75. I'd suggest to review all caller of `get_mclen()` in w3m.

**Comment by tats** [comment]
Fixed, thank you.

**Comment by tats** [comment]
Patch updated.
