### ISSUE TITLE
heap-buffer-overflow read in form_update_line()

### ISSUE THREAD

**Issue by kcwu** [tats/w3m#75]
input (`xxd cases/tats-w3m-75`)
```
00000000: 3c6d 6574 6120 6368 6172 7365 743d 6762  <meta charset=gb
00000010: 3138 3033 303e 3030 3030 3030 3030 3030  18030>0000000000
00000020: 3030 3030 3030 3030 3030 3030 3030 3030  0000000000000000
00000030: 3030 3030 3030 3030 3030 3030 3030 3030  0000000000000000
00000040: 3030 3030 3030 2030 3030 3030 3030 3030  000000 000000000
00000050: 3030 3030 3030 3030 3030 3030 3030 3030  0000000000000000
00000060: 3030 3030 3030 0d30 3030 3030 3030 3030  000000.000000000
00000070: 3030 3030 3030 303c 696e 7075 7420 7661  0000000<input va
00000080: 6c75 653d 3030 3030 3030 3030 3080 3e3c  lue=000000000.><
00000090: 696e 7075 743e                           input>
```

how to reproduce:
```
ASAN_OPTIONS=abort_on_error=1:detect_leaks=0 LD_LIBRARY_PATH=./notgc ./w3m-tats.asan -T text/html -dump cases/tats-w3m-75
```

stderr:
```
=================================================================
==1368100==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200000afdc at pc 0x000000631f02 bp 0x7ffdbd0ef170 sp 0x7ffdbd0ef168
READ of size 1 at 0x60200000afdc thread T0
    #0 0x631f01 in form_update_line /targets/w3m-tats/form.c:284:36
    #1 0x630982 in formUpdateBuffer /targets/w3m-tats/form.c:495:12
    #2 0x631ca7 in formResetBuffer /targets/w3m-tats/form.c:272:2
    #3 0x55bdd8 in loadHTMLBuffer /targets/w3m-tats/file.c:6800:2
    #4 0x55ee64 in loadSomething /targets/w3m-tats/file.c:224:16
    #5 0x5535ac in loadGeneralFile /targets/w3m-tats/file.c:2241:6
    #6 0x4f9202 in main /targets/w3m-tats/main.c:1017:12
    #7 0x7f535386cf44 in __libc_start_main /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:287
    #8 0x41bf25 in _start (/w3m-tats.asan+0x41bf25)

0x60200000afdc is located 1 bytes to the right of 11-byte region [0x60200000afd0,0x60200000afdb)
allocated by thread T0 here:
    #0 0x4c6288 in __interceptor_malloc (/w3m-tats.asan+0x4c6288)
    #1 0x7f5354fbac21 in GC_malloc_atomic /notgc/notgc.c:275
    #2 0x62cd47 in formList_addInput /targets/w3m-tats/form.c:121:35
    #3 0x6cd378 in registerForm /targets/w3m-tats/anchor.c:94:10
    #4 0x59d5df in HTMLlineproc2body /targets/w3m-tats/file.c:5901:8
    #5 0x59723e in HTMLlineproc2 /targets/w3m-tats/file.c:6208:5
    #6 0x5a672e in loadHTMLstream /targets/w3m-tats/file.c:7302:5
    #7 0x55bbf8 in loadHTMLBuffer /targets/w3m-tats/file.c:6794:5
    #8 0x55ee64 in loadSomething /targets/w3m-tats/file.c:224:16
    #9 0x5535ac in loadGeneralFile /targets/w3m-tats/file.c:2241:6
    #10 0x4f9202 in main /targets/w3m-tats/main.c:1017:12
    #11 0x7f535386cf44 in __libc_start_main /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:287

SUMMARY: AddressSanitizer: heap-buffer-overflow /targets/w3m-tats/form.c:284:36 in form_update_line
Shadow bytes around the buggy address:
  0x0c047fff95a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff95b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff95c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff95d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff95e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa 00 07
=>0x0c047fff95f0: fa fa 00 fa fa fa 01 fa fa fa 00[03]fa fa 00 00
  0x0c047fff9600: fa fa 01 fa fa fa 00 00 fa fa 00 00 fa fa 00 00
  0x0c047fff9610: fa fa 00 00 fa fa 00 00 fa fa 00 00 fa fa 00 00
  0x0c047fff9620: fa fa 00 00 fa fa 00 00 fa fa 00 00 fa fa 00 00
  0x0c047fff9630: fa fa 00 00 fa fa 00 00 fa fa 00 00 fa fa 00 00
  0x0c047fff9640: fa fa 00 00 fa fa 00 00 fa fa 00 03 fa fa 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==1368100==ABORTING
```

This is detected with help of dummy libgc wrapper. See http://github.com/kcwu/fuzzing-w3m/notgc for detail.
More detail to reproduce please see http://github.com/kcwu/fuzzing-w3m

For your convenience,
gdbline:
LD_LIBRARY_PATH=./notgc ASAN_OPTIONS=abort_on_error=1:detect_leaks=0 gdb --args ./w3m-tats.asan -T text/html -dump cases/tats-w3m-75

this is found by afl-fuzz

**Comment by kcwu** [comment]
similar to issue #73. form.c
```
284         for (p = *str, w = 0, pos = 0; *p && w < width;) {
...
287             c_len = get_mclen(p);
...
318             p += c_len;
```
`c_len=3`, `p` jump beyond the end of string.

**Comment by tats** [comment]
Fixed, thank you.

**Comment by tats** [comment]
Patch updated by https://github.com/tats/w3m/commit/6eea841d3a0f8dc539584dc67b15f585a8213775
