### ISSUE TITLE
heap-buffer-overflow read in visible_length_plain()

### ISSUE THREAD

**Issue by kcwu** [tats/w3m#76]
input (`xxd cases/tats-w3m-76`)
```
00000000: 3c6d 6574 6120 6368 6172 7365 743d 6762  <meta charset=gb
00000010: 3138 3033 303e 3c74 6162 6c65 3e3c 786d  18030><table><xm
00000020: 703e 0d80                                p>..
```

how to reproduce:
```
ASAN_OPTIONS=abort_on_error=1:detect_leaks=0 LD_LIBRARY_PATH=./notgc ./w3m-tats.asan -T text/html -dump cases/tats-w3m-76
```

stderr:
```
=================================================================
==3432414==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60300000d9e0 at pc 0x0000005f828c bp 0x7ffccf5d3fa0 sp 0x7ffccf5d3f98
READ of size 1 at 0x60300000d9e0 thread T0
    #0 0x5f828b in visible_length_plain /targets/w3m-tats/table.c:514:12
    #1 0x6209b1 in maximum_visible_length_plain /targets/w3m-tats/table.c:551:12
    #2 0x617611 in feed_table /targets/w3m-tats/table.c:3290:7
    #3 0x591c7c in HTMLlineproc0 /targets/w3m-tats/file.c:6434:14
    #4 0x5a5d4c in loadHTMLstream /targets/w3m-tats/file.c:7265:2
    #5 0x55bbf8 in loadHTMLBuffer /targets/w3m-tats/file.c:6794:5
    #6 0x55ee64 in loadSomething /targets/w3m-tats/file.c:224:16
    #7 0x5535ac in loadGeneralFile /targets/w3m-tats/file.c:2241:6
    #8 0x4f9202 in main /targets/w3m-tats/main.c:1017:12
    #9 0x7f0e0434bf44 in __libc_start_main /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:287
    #10 0x41bf25 in _start (/w3m-tats.asan+0x41bf25)

0x60300000d9e0 is located 0 bytes to the right of 32-byte region [0x60300000d9c0,0x60300000d9e0)
allocated by thread T0 here:
    #0 0x4c6288 in __interceptor_malloc (/w3m-tats.asan+0x4c6288)
    #1 0x7f0e05a99c21 in GC_malloc_atomic /notgc/notgc.c:275
    #2 0x590325 in HTMLlineproc0 /targets/w3m-tats/file.c:6330:14
    #3 0x5a5d4c in loadHTMLstream /targets/w3m-tats/file.c:7265:2
    #4 0x55bbf8 in loadHTMLBuffer /targets/w3m-tats/file.c:6794:5
    #5 0x55ee64 in loadSomething /targets/w3m-tats/file.c:224:16
    #6 0x5535ac in loadGeneralFile /targets/w3m-tats/file.c:2241:6
    #7 0x4f9202 in main /targets/w3m-tats/main.c:1017:12
    #8 0x7f0e0434bf44 in __libc_start_main /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:287

SUMMARY: AddressSanitizer: heap-buffer-overflow /targets/w3m-tats/table.c:514:12 in visible_length_plain
Shadow bytes around the buggy address:
  0x0c067fff9ae0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff9af0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff9b00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff9b10: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff9b20: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c067fff9b30: fa fa fa fa fa fa fa fa 00 00 00 00[fa]fa 00 00
  0x0c067fff9b40: 01 fa fa fa 00 00 00 fa fa fa 00 00 00 fa fa fa
  0x0c067fff9b50: 00 00 00 fa fa fa 00 00 00 00 fa fa 00 00 00 00
  0x0c067fff9b60: fa fa 00 00 00 00 fa fa 00 00 00 00 fa fa 00 00
  0x0c067fff9b70: 00 00 fa fa 00 00 00 fa fa fa 00 00 00 00 fa fa
  0x0c067fff9b80: 00 00 00 00 fa fa 00 00 00 00 fa fa fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==3432414==ABORTING
```

This is detected with help of dummy libgc wrapper. See http://github.com/kcwu/fuzzing-w3m/notgc for detail.
More detail to reproduce please see http://github.com/kcwu/fuzzing-w3m

For your convenience,
gdbline:
LD_LIBRARY_PATH=./notgc ASAN_OPTIONS=abort_on_error=1:detect_leaks=0 gdb --args ./w3m-tats.asan -T text/html -dump cases/tats-w3m-76

This is found by afl-fuzz

**Comment by kcwu** [comment]
similar to issue #73. table.c
```
514         while (*str) {
...
530                 str += get_mclen(str);
```
the result of `get_mclen(str)` is 3. `str` jump beyond the end of string.

**Comment by tats** [comment]
Fixed, thank you.

**Comment by tats** [comment]
Patch updated.
