### ISSUE TITLE
heap-buffer-overflow read in wtf_is_hangul()

### ISSUE THREAD

**Issue by kcwu** [tats/w3m#77]
input (`xxd cases/tats-w3m-77`)
```
00000000: 3c6d 6574 6120 6368 6172 7365 743d 6762  <meta charset=gb
00000010: 3138 3033 303e 0af8 f8f8 30f8 40f8 f8f8  18030>....0.@...
00000020: f8f8 f8f8 f8f8 f8f8 3080 3030 3030 3030  ........0.000000
00000030: 3030 3030 3030 3030 3030 3030 3030 3030  0000000000000000
00000040: 80f8 f8f8 f8f8 f83c                      .......<
```

how to reproduce:
```
ASAN_OPTIONS=abort_on_error=1:detect_leaks=0 LD_LIBRARY_PATH=./notgc ./w3m-tats.asan -T text/html -dump cases/tats-w3m-77
```

stderr:
```
=================================================================
==3436904==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60700000d6cc at pc 0x00000075c836 bp 0x7ffe84655bd0 sp 0x7ffe84655bc8
READ of size 1 at 0x60700000d6cc thread T0
    #0 0x75c835 in wtf_is_hangul /targets/w3m-tats/libwc/wtf.c:554:30
    #1 0x594082 in HTMLlineproc0 /targets/w3m-tats/file.c:6579:16
    #2 0x5a5d4c in loadHTMLstream /targets/w3m-tats/file.c:7265:2
    #3 0x55bbf8 in loadHTMLBuffer /targets/w3m-tats/file.c:6794:5
    #4 0x55ee64 in loadSomething /targets/w3m-tats/file.c:224:16
    #5 0x5535ac in loadGeneralFile /targets/w3m-tats/file.c:2241:6
    #6 0x4f9202 in main /targets/w3m-tats/main.c:1017:12
    #7 0x7ff558976f44 in __libc_start_main /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:287
    #8 0x41bf25 in _start (/w3m-tats.asan+0x41bf25)

0x60700000d6cc is located 0 bytes to the right of 76-byte region [0x60700000d680,0x60700000d6cc)
allocated by thread T0 here:
    #0 0x4c6288 in __interceptor_malloc (/w3m-tats.asan+0x4c6288)
    #1 0x7ff55a0c4c21 in GC_malloc_atomic /notgc/notgc.c:275
    #2 0x5d6b5b in read_token /targets/w3m-tats/etc.c:825:6
    #3 0x591315 in HTMLlineproc0 /targets/w3m-tats/file.c:6374:6
    #4 0x5a5d4c in loadHTMLstream /targets/w3m-tats/file.c:7265:2
    #5 0x55bbf8 in loadHTMLBuffer /targets/w3m-tats/file.c:6794:5
    #6 0x55ee64 in loadSomething /targets/w3m-tats/file.c:224:16
    #7 0x5535ac in loadGeneralFile /targets/w3m-tats/file.c:2241:6
    #8 0x4f9202 in main /targets/w3m-tats/main.c:1017:12
    #9 0x7ff558976f44 in __libc_start_main /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:287

SUMMARY: AddressSanitizer: heap-buffer-overflow /targets/w3m-tats/libwc/wtf.c:554:30 in wtf_is_hangul
Shadow bytes around the buggy address:
  0x0c0e7fff9a80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0e7fff9a90: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0e7fff9aa0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0e7fff9ab0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0e7fff9ac0: fa fa 00 00 00 00 00 00 00 00 00 03 fa fa fa fa
=>0x0c0e7fff9ad0: 00 00 00 00 00 00 00 00 00[04]fa fa fa fa fd fd
  0x0c0e7fff9ae0: fd fd fd fd fd fd fd fa fa fa fa fa 00 00 00 00
  0x0c0e7fff9af0: 00 00 00 00 01 fa fa fa fa fa 00 00 00 00 00 00
  0x0c0e7fff9b00: 00 00 00 03 fa fa fa fa 00 00 00 00 00 00 00 00
  0x0c0e7fff9b10: 00 00 fa fa fa fa 00 00 00 00 00 00 00 00 00 fa
  0x0c0e7fff9b20: fa fa fa fa 00 00 00 00 00 00 00 00 00 fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==3436904==ABORTING
```

This is detected with help of dummy libgc wrapper. See http://github.com/kcwu/fuzzing-w3m/notgc for detail.
More detail to reproduce please see http://github.com/kcwu/fuzzing-w3m

For your convenience,
gdbline:
LD_LIBRARY_PATH=./notgc ASAN_OPTIONS=abort_on_error=1:detect_leaks=0 gdb --args ./w3m-tats.asan -T text/html -dump cases/tats-w3m-77

This is found by afl-fuzz

**Comment by kcwu** [comment]
wtf.c
```
552             wc_uchar f = (*(++p) & 0x7f) >> 2;
553             if (f == WC_F_UCS2)
554                 return wc_is_ucs_hangul(wtf_to_wcs16(p));
```
At line 552, `p[0]=0x89`, `p[1]=0`.
At line 554, `p[0]=0` (end of string). But `wtf_to_wcs16()` want to read `p[0]`,`p[1]`,and `p[2]`.

**Comment by tats** [comment]
Fixed, thank you.

**Comment by tats** [comment]
Patch updated.
