### ISSUE TITLE
heap-buffer-overflow read in textfieldrep()

### ISSUE THREAD

**Issue by kcwu** [tats/w3m#79]
input (`xxd cases/tats-w3m-79`)
```
00000000: 3c6d 6574 6120 6368 6172 7365 743d 6762  <meta charset=gb
00000010: 3138 3033 303e 0d3c 696e 7075 7420 7661  18030>.<input va
00000020: 6c75 653d 803e                           lue=.>
```

how to reproduce:
```
ASAN_OPTIONS=abort_on_error=1:detect_leaks=0 LD_LIBRARY_PATH=./notgc ./w3m-tats.asan -T text/html -dump cases/tats-w3m-79
```

stderr:
```
=================================================================
==3106604==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020000026d2 at pc 0x000000466cfa bp 0x7ffddb12fb40 sp 0x7ffddb12f2f0
READ of size 3 at 0x6020000026d2 thread T0
    #0 0x466cf9 in memmove /home/kcwu/clang/llvm/llvm/projects/compiler-rt/lib/asan/asan_interceptors.cc:451
    #1 0x704e3b in Strcat_charp_n /targets/w3m-tats/Str.c:201:5
    #2 0x654b4f in textfieldrep /targets/w3m-tats/form.c:547:6
    #3 0x58f553 in process_input /targets/w3m-tats/file.c:3708:15
    #4 0x5ad666 in HTMLtagproc1 /targets/w3m-tats/file.c:5120:8
    #5 0x5b35b1 in HTMLlineproc0 /targets/w3m-tats/file.c:6489:10
    #6 0x5c6699 in loadHTMLstream /targets/w3m-tats/file.c:7265:2
    #7 0x57be58 in loadHTMLBuffer /targets/w3m-tats/file.c:6794:5
    #8 0x57f0a4 in loadSomething /targets/w3m-tats/file.c:224:16
    #9 0x573833 in loadGeneralFile /targets/w3m-tats/file.c:2241:6
    #10 0x51967c in main /targets/w3m-tats/main.c:1017:12
    #11 0x7f3db1c07f44 in __libc_start_main /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:287
    #12 0x41cf6b in _start (/w3m-tats.asan+0x41cf6b)

0x6020000026d2 is located 0 bytes to the right of 2-byte region [0x6020000026d0,0x6020000026d2)
allocated by thread T0 here:
    #0 0x4e01a6 in __interceptor_malloc /home/kcwu/clang/llvm/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:64
    #1 0x7f3db3355c21 in GC_malloc_atomic /notgc/notgc.c:275
    #2 0x58f4ec in process_input /targets/w3m-tats/file.c:3708:28
    #3 0x5ad666 in HTMLtagproc1 /targets/w3m-tats/file.c:5120:8
    #4 0x5b35b1 in HTMLlineproc0 /targets/w3m-tats/file.c:6489:10
    #5 0x5c6699 in loadHTMLstream /targets/w3m-tats/file.c:7265:2
    #6 0x57be58 in loadHTMLBuffer /targets/w3m-tats/file.c:6794:5
    #7 0x57f0a4 in loadSomething /targets/w3m-tats/file.c:224:16
    #8 0x573833 in loadGeneralFile /targets/w3m-tats/file.c:2241:6
    #9 0x51967c in main /targets/w3m-tats/main.c:1017:12
    #10 0x7f3db1c07f44 in __libc_start_main /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:287

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/kcwu/clang/llvm/llvm/projects/compiler-rt/lib/asan/asan_interceptors.cc:451 in memmove
Shadow bytes around the buggy address:
  0x0c047fff8480: fa fa 00 00 fa fa 00 00 fa fa 00 00 fa fa fd fd
  0x0c047fff8490: fa fa 00 00 fa fa 00 05 fa fa 00 00 fa fa 00 00
  0x0c047fff84a0: fa fa 00 fa fa fa 00 00 fa fa 00 00 fa fa 00 00
  0x0c047fff84b0: fa fa 00 00 fa fa 00 00 fa fa 05 fa fa fa 00 00
  0x0c047fff84c0: fa fa 00 00 fa fa 00 00 fa fa 05 fa fa fa 00 00
=>0x0c047fff84d0: fa fa 00 00 fa fa 00 00 fa fa[02]fa fa fa 00 00
  0x0c047fff84e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff84f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8500: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8510: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8520: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==3106604==ABORTING
```

This is detected with help of dummy libgc wrapper. See http://github.com/kcwu/fuzzing-w3m/notgc for detail.
More detail to reproduce please see http://github.com/kcwu/fuzzing-w3m

For your convenience,
gdbline:
LD_LIBRARY_PATH=./notgc ASAN_OPTIONS=abort_on_error=1:detect_leaks=0 gdb --args ./w3m-tats.asan -T text/html -dump cases/tats-w3m-79

**Comment by kcwu** [comment]
p.s. because ASan didn't intercept bcopy(), it cannot detect this issue. This report was detected by ASan with my local patch (see https://github.com/google/sanitizers/issues/750 for more detail). In the meantime, you can apply my patch, or use valgrind as workaround.

**Comment by kcwu** [comment]
form.c
```
526         for (i = 0; i < s->length; i += c_len) {
527             c_type = get_mctype((unsigned char *)&s->ptr[i]);
528             c_len = get_mclen(&s->ptr[i]);
...
547                 Strcat_charp_n(n, &s->ptr[i], c_len);
```
where `c_len=3` but `i+c_len` is beyond the end of `s->ptr`.

**Comment by tats** [comment]
Patch updated.
