### ISSUE TITLE
heap-buffer-overflow read in proc_mchar()

### ISSUE THREAD

**Issue by kcwu** [tats/w3m#80]
input (`xxd cases/tats-w3m-80`)
```
00000000: 3c6d 6574 6100 6368 6172 7365 743d 6762  <meta.charset=gb
00000010: 3138 3033 303e 3c78 6d70 3e3c 690d 803c  18030><xmp><i..<
00000020: 303e                                     0>
```

how to reproduce:
```
ASAN_OPTIONS=abort_on_error=1:detect_leaks=0 LD_LIBRARY_PATH=./notgc ./w3m-tats.asan -T text/html -dump cases/tats-w3m-80
```

stderr:
```
=================================================================
==3128077==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000002575 at pc 0x000000466cfa bp 0x7ffc0a25c160 sp 0x7ffc0a25b910
READ of size 3 at 0x602000002575 thread T0
    #0 0x466cf9 in memmove /home/kcwu/clang/llvm/llvm/projects/compiler-rt/lib/asan/asan_interceptors.cc:451
    #1 0x704e3b in Strcat_charp_n /targets/w3m-tats/Str.c:201:5
    #2 0x5c324d in proc_mchar /targets/w3m-tats/file.c:2610:5
    #3 0x5b4801 in HTMLlineproc0 /targets/w3m-tats/file.c:6555:4
    #4 0x5c6699 in loadHTMLstream /targets/w3m-tats/file.c:7265:2
    #5 0x57be58 in loadHTMLBuffer /targets/w3m-tats/file.c:6794:5
    #6 0x57f0a4 in loadSomething /targets/w3m-tats/file.c:224:16
    #7 0x573833 in loadGeneralFile /targets/w3m-tats/file.c:2241:6
    #8 0x51967c in main /targets/w3m-tats/main.c:1017:12
    #9 0x7f7438edbf44 in __libc_start_main /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:287
    #10 0x41cf6b in _start (/w3m-tats.asan+0x41cf6b)

0x602000002575 is located 0 bytes to the right of 5-byte region [0x602000002570,0x602000002575)
allocated by thread T0 here:
    #0 0x4e01a6 in __interceptor_malloc /home/kcwu/clang/llvm/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:64
    #1 0x7f743a629c21 in GC_malloc_atomic /notgc/notgc.c:275
    #2 0x5b25f0 in HTMLlineproc0 /targets/w3m-tats/file.c:6407:13
    #3 0x5c6699 in loadHTMLstream /targets/w3m-tats/file.c:7265:2
    #4 0x57be58 in loadHTMLBuffer /targets/w3m-tats/file.c:6794:5
    #5 0x57f0a4 in loadSomething /targets/w3m-tats/file.c:224:16
    #6 0x573833 in loadGeneralFile /targets/w3m-tats/file.c:2241:6
    #7 0x51967c in main /targets/w3m-tats/main.c:1017:12
    #8 0x7f7438edbf44 in __libc_start_main /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:287

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/kcwu/clang/llvm/llvm/projects/compiler-rt/lib/asan/asan_interceptors.cc:451 in memmove
Shadow bytes around the buggy address:
  0x0c047fff8450: fa fa 00 00 fa fa 04 fa fa fa 04 fa fa fa 00 00
  0x0c047fff8460: fa fa 00 00 fa fa 00 00 fa fa 00 01 fa fa 00 00
  0x0c047fff8470: fa fa 00 00 fa fa 00 00 fa fa 04 fa fa fa 00 00
  0x0c047fff8480: fa fa 00 00 fa fa 01 fa fa fa 00 fa fa fa 00 00
  0x0c047fff8490: fa fa 00 00 fa fa fd fa fa fa 06 fa fa fa 00 00
=>0x0c047fff84a0: fa fa 01 fa fa fa 00 fa fa fa 00 00 fa fa[05]fa
  0x0c047fff84b0: fa fa 00 00 fa fa 00 00 fa fa 00 00 fa fa fa fa
  0x0c047fff84c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff84d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff84e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff84f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==3128077==ABORTING
```

This is detected with help of dummy libgc wrapper. See http://github.com/kcwu/fuzzing-w3m/notgc for detail.
More detail to reproduce please see http://github.com/kcwu/fuzzing-w3m

For your convenience,
gdbline:
LD_LIBRARY_PATH=./notgc ASAN_OPTIONS=abort_on_error=1:detect_leaks=0 gdb --args ./w3m-tats.asan -T text/html -dump cases/tats-w3m-80

this is found by afl-fuzz

**Comment by kcwu** [comment]
p.s. this is detected by ASan with my patch.

**Comment by kcwu** [comment]
similar to issue #79. file.c
```
2610        Strcat_charp_n(obuf->line, *str, get_mclen(*str));
```
where `get_mclen(*str)=3`, but `*str+3` is beyond the end of `*str`.

**Comment by tats** [comment]
Fixed, thank you.

**Comment by tats** [comment]
Patch updated.
