### ISSUE TITLE
heap-buffer-overflow read in HTMLlineproc2body()

### ISSUE THREAD

**Issue by kcwu** [tats/w3m#83]
input (`xxd cases/tats-w3m-83`)
```
00000000: 3c6d 6574 6120 6368 6172 7365 743d 6762  <meta charset=gb
00000010: 3138 3033 303e 0d30 30ff 3086 3030 3030  18030>.00.0.0000
00000020: 3030 bd30 3092 3030 3082 0080 3c74       00.00.000...<t
```

how to reproduce:
```
ASAN_OPTIONS=abort_on_error=1:detect_leaks=0 LD_LIBRARY_PATH=./notgc ./w3m-tats.asan -T text/html -dump cases/tats-w3m-83
```

stderr:
```
=================================================================
==980622==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60300000db90 at pc 0x000000599210 bp 0x7fffedeab710 sp 0x7fffedeab708
READ of size 1 at 0x60300000db90 thread T0
    #0 0x59920f in HTMLlineproc2body /targets/w3m-tats/file.c:5595:4
    #1 0x5975ee in HTMLlineproc2 /targets/w3m-tats/file.c:6209:5
    #2 0x5a699e in loadHTMLstream /targets/w3m-tats/file.c:7303:5
    #3 0x55bfa8 in loadHTMLBuffer /targets/w3m-tats/file.c:6795:5
    #4 0x55f214 in loadSomething /targets/w3m-tats/file.c:224:16
    #5 0x55395c in loadGeneralFile /targets/w3m-tats/file.c:2241:6
    #6 0x4f95b2 in main /targets/w3m-tats/main.c:1017:12
    #7 0x7f803fbb8f44 in __libc_start_main /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:287
    #8 0x41bfd5 in _start (/w3m-tats.asan+0x41bfd5)

0x60300000db90 is located 0 bytes to the right of 32-byte region [0x60300000db70,0x60300000db90)
allocated by thread T0 here:
    #0 0x4c6508 in __interceptor_malloc /home/kcwu/clang/llvm/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:52
    #1 0x7f8041306c21 in GC_malloc_atomic /notgc/notgc.c:275
    #2 0x566715 in init_henv /targets/w3m-tats/file.c:6938:18
    #3 0x5a4cee in loadHTMLstream /targets/w3m-tats/file.c:7193:5
    #4 0x55bfa8 in loadHTMLBuffer /targets/w3m-tats/file.c:6795:5
    #5 0x55f214 in loadSomething /targets/w3m-tats/file.c:224:16
    #6 0x55395c in loadGeneralFile /targets/w3m-tats/file.c:2241:6
    #7 0x4f95b2 in main /targets/w3m-tats/main.c:1017:12
    #8 0x7f803fbb8f44 in __libc_start_main /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:287

SUMMARY: AddressSanitizer: heap-buffer-overflow /targets/w3m-tats/file.c:5595:4 in HTMLlineproc2body
Shadow bytes around the buggy address:
  0x0c067fff9b20: fa fa fa fa fa fa 00 00 00 fa fa fa 00 00 00 00
  0x0c067fff9b30: fa fa 00 00 01 fa fa fa 00 00 00 00 fa fa fd fd
  0x0c067fff9b40: fd fd fa fa fd fd fd fa fa fa 00 00 00 00 fa fa
  0x0c067fff9b50: 00 00 00 00 fa fa 00 00 00 00 fa fa 00 00 00 00
  0x0c067fff9b60: fa fa 00 00 00 fa fa fa 00 00 00 00 fa fa 00 00
=>0x0c067fff9b70: 00 00[fa]fa 00 00 00 00 fa fa fd fd fd fd fa fa
  0x0c067fff9b80: 00 00 00 00 fa fa 00 00 00 00 fa fa 00 00 00 fa
  0x0c067fff9b90: fa fa 00 00 00 00 fa fa 00 00 02 fa fa fa 00 00
  0x0c067fff9ba0: 02 fa fa fa 00 00 00 00 fa fa 00 00 00 00 fa fa
  0x0c067fff9bb0: 00 00 00 fa fa fa fd fd fd fd fa fa fd fd fd fd
  0x0c067fff9bc0: fa fa fd fd fd fd fa fa 00 00 01 fa fa fa fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==980622==ABORTING
```

This is detected with help of dummy libgc wrapper. See http://github.com/kcwu/fuzzing-w3m/notgc for detail.
More detail to reproduce please see http://github.com/kcwu/fuzzing-w3m

For your convenience,
gdbline:
LD_LIBRARY_PATH=./notgc ASAN_OPTIONS=abort_on_error=1:detect_leaks=0 gdb --args ./w3m-tats.asan -T text/html -dump cases/tats-w3m-83

found by afl-fuzz

**Comment by kcwu** [comment]
file.c
```
5587                    int len = get_mclen(str);
5588    #endif
5589                    PPUSH(mode | effect | ex_efct(ex_effect), *(str++));
5590    #ifdef USE_M17N
5591                    if (--len) {
(gdb)
5592                        mode = (mode & ~PC_WCHAR1) | PC_WCHAR2;
5593                        while (len--) {
5594                            PSIZE;
5595                            PPUSH(mode | effect | ex_efct(ex_effect), *(str++));
5596                        }
```
at line 5587, `len=3`. then `str` goes beyond the end of string at line 5595.

**Comment by kcwu** [comment]
BTW, many `get_mclen()` in the same function have the same issue.

**Comment by tats** [comment]
> BTW, many get_mclen() in the same function have the same issue.

Hopefully, all caller of get_mclen() fixed.
