### ISSUE TITLE
heap-buffer-overflow read in skip_space()

### ISSUE THREAD

**Issue by kcwu** [tats/w3m#84]
input (`xxd cases/tats-w3m-84`)
```
00000000: 3c6d 6574 6120 6368 6172 7365 743d 6762  <meta charset=gb
00000010: 3138 3033 303e 0a3c 7461 626c 653e 3030  18030>.<table>00
00000020: 3030 3030 3030 3030 3030 3030 3030 308f  000000000000000.
00000030: 3030 bc30 3030 3030 803c                 00.00000.<
```

how to reproduce:
```
ASAN_OPTIONS=abort_on_error=1:detect_leaks=0 LD_LIBRARY_PATH=./notgc ./w3m-tats.asan -T text/html -dump cases/tats-w3m-84
```

stderr:
```
=================================================================
==3438691==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6030000015f0 at pc 0x000000466d8a bp 0x7ffff03196e0 sp 0x7ffff0318e90
READ of size 3 at 0x6030000015f0 thread T0
    #0 0x466d89 in memmove /home/kcwu/clang/llvm/llvm/projects/compiler-rt/lib/asan/asan_interceptors.cc:451
    #1 0x704937 in Strcopy_charp_n /targets/w3m-tats/Str.c:179:5
    #2 0x6339ac in skip_space /targets/w3m-tats/table.c:2306:2
    #3 0x636c9b in feed_table /targets/w3m-tats/table.c:3253:6
    #4 0x5b2922 in HTMLlineproc0 /targets/w3m-tats/file.c:6435:14
    #5 0x5c6559 in loadHTMLstream /targets/w3m-tats/file.c:7266:2
    #6 0x57be58 in loadHTMLBuffer /targets/w3m-tats/file.c:6795:5
    #7 0x57f0a4 in loadSomething /targets/w3m-tats/file.c:224:16
    #8 0x573833 in loadGeneralFile /targets/w3m-tats/file.c:2241:6
    #9 0x51967c in main /targets/w3m-tats/main.c:1017:12
    #10 0x7f202b793f44 in __libc_start_main /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:287
    #11 0x41cf6b in _start (/w3m-tats.asan+0x41cf6b)

0x6030000015f0 is located 0 bytes to the right of 32-byte region [0x6030000015d0,0x6030000015f0)
allocated by thread T0 here:
    #0 0x4e0236 in __interceptor_malloc /home/kcwu/clang/llvm/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:64
    #1 0x7f202cee1c21 in GC_malloc_atomic /notgc/notgc.c:275
    #2 0x5b0fcb in HTMLlineproc0 /targets/w3m-tats/file.c:6331:14
    #3 0x5c6559 in loadHTMLstream /targets/w3m-tats/file.c:7266:2
    #4 0x57be58 in loadHTMLBuffer /targets/w3m-tats/file.c:6795:5
    #5 0x57f0a4 in loadSomething /targets/w3m-tats/file.c:224:16
    #6 0x573833 in loadGeneralFile /targets/w3m-tats/file.c:2241:6
    #7 0x51967c in main /targets/w3m-tats/main.c:1017:12
    #8 0x7f202b793f44 in __libc_start_main /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:287

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/kcwu/clang/llvm/llvm/projects/compiler-rt/lib/asan/asan_interceptors.cc:451 in memmove
Shadow bytes around the buggy address:
  0x0c067fff8260: 00 00 02 fa fa fa 00 00 02 fa fa fa 00 00 00 00
  0x0c067fff8270: fa fa 00 00 00 fa fa fa 00 00 00 00 fa fa 00 00
  0x0c067fff8280: 00 00 fa fa fd fd fd fd fa fa 00 00 00 00 fa fa
  0x0c067fff8290: 00 00 00 00 fa fa 00 00 00 00 fa fa 00 00 00 fa
  0x0c067fff82a0: fa fa 00 00 00 00 fa fa 00 00 00 00 fa fa 00 00
=>0x0c067fff82b0: 00 00 fa fa 00 00 00 00 fa fa 00 00 00 00[fa]fa
  0x0c067fff82c0: 00 00 00 00 fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff82d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff82e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff82f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff8300: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==3438691==ABORTING
```

This is detected with help of dummy libgc wrapper. See http://github.com/kcwu/fuzzing-w3m/notgc for detail.
More detail to reproduce please see http://github.com/kcwu/fuzzing-w3m

For your convenience,
gdbline:
LD_LIBRARY_PATH=./notgc ASAN_OPTIONS=abort_on_error=1:detect_leaks=0 gdb --args ./w3m-tats.asan -T text/html -dump cases/tats-w3m-84

found by afl-fuzz

**Comment by kcwu** [comment]
Str.c
```
2264        while (line < linez) {
2265            char *save = line, *c = line;
...
2269            wlen = plen = get_mclen(line);
...
2281                        c = conv_entity(ec);
...
2285                        plen = get_mclen(c);
...
2306            set_prevchar(prevchar, c, plen);
```
where `plen=3`. `set_prevchar=Strcopy_charp_n`, which will read `plen` bytes, beyond the end of string.

**Comment by tats** [comment]
Fixed, thank you.
